---
- name: Debug system patch status
  ansible.builtin.debug:
    msg:
      - "-----"
      - "system is virtual: {{ ansible_virtualization_type | default('') }}"
      - "system policy: make snapshot {{ VMWaresnapshot | default('') }}"
      - "-----"
      - "patching policy: free space needed boot: {{ app_min_boot_space_needed }}"
      - "free space /boot: {{ boot_freespace.stdout_lines[1] | float if boot_freespace is defined else '' }}"
      - "patching policy: free space needed var/cache: {{ app_min_var_space_needed }}"
      - "free space /var/cache: {{ var_freespace.stdout_lines[1] | float }}"
      - "-----"
      - "ansible_distribution: {{ ansible_distribution }}"
      - "system policy: subscription manager - must be registered: {{ sp_system_must_be_registered if sp_system_must_be_registered is defined else '' }}"
      - "system is actually registered - subscription manager: {{ appo_system_registered if appo_system_registered is defined else '' }}"
      - "-----"
      - "were package updates available: {{ appo_package_updates_available | default('') }}"
      - "did package updates succeed: {{ appo_package_update_suceeded | default('') }}"
      - "-----"
      - "original kernel version: {{ LAST_KERNEL.stdout | default('') }}"
      - "reboot needed due to kernel updates: {{ appo_kernel_reboot_needed | default('') }}"
      - "reboot needed due to library updates: {{ appo_lib_reboot_needed | default('') }}"
      - "reboot policy: {{ app_default_reboot_action }}"
      - "reboot module result: {{ appo_reboot_actioned | default('') }}"
      - "post reboot kernel version: {{ appo_post_patch_kernel | default('') }}"
      - "-----"
      - package update output {{ pkg_update_result | default('') }}
      - "-----"
      - reboot need check output (unreliable in checkmode) {{ nr_reboot | default('') }}
